config/routes.rb
SecretShareApp::Application.routes.draw do
  resource :sessions
  resources :users
  resources :secrets
  root to: 'dashboard#index'

end

app/models/secret.rb
class Secret < ActiveRecord::Base
  attr_accessible :body, :photo, :user_id
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :secrets
  attr_accessible :name, :email, :password, :password_confirmation
  validates :name, :uniqueness => true, :presence => true
  validates :email, :uniqueness => true, :presence => true
  validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/, :on => :create
  validates :password, :length => { minimum: 5,
            :too_short => "must have at least 5 letters"}
  has_secure_password


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :current_user

  def current_user
    if session[:session_token]
      p @current_user
      @current_user = User.find_by_session_token(session[:session_token])
    else
      redirect_to new_sessions_path
    end
  end


end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
  end
end

app/controllers/secrets_controller.rb
class SecretsController < ApplicationController
  def new
    @secret = Secret.new(params[:secret])
  end

  def create
    @secret = Secret.new(params[:secret])
    @secret.user_id = @current_user.id
    @secret.save
    redirect_to secrets_path
  end

  def index
    @secrets = Secret.where("user_id = #{current_user.id}")
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_filter :current_user, :except => [:new, :create]

  def create
    @user = User.find_by_name(params[:name])
    if @user && @user.authenticate(params[:password])
      @user.update_attribute(:session_token, SecureRandom.base64)
      session[:session_token] = @user.session_token
      redirect_to root_url
    else
      flash.notice = "Invalid Login"
      render new_sessions_path
    end
  end

  def new
  end

  def destroy
    session[:session_token] = nil
    redirect_to new_sessions_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :current_user, :except => [:new, :create]

  def create
    @user = User.new(params[:user])
    if @user.save
      UserMailer.welcome_email(@user).deliver
      redirect_to secrets_path
    else
      render 'new'
    end
  end

  def new
    @user = User.new(params[:user])
  end

  def index

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/secrets_helper.rb
module SecretsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/dashboard/index.html.erb
<h1>Welcome</h1>

Welcome <%= @current_user.name %>
<br>

<%= link_to "ALL THE SECRETS", secrets_path %>
<br>

<%= link_to "Create Secret", new_secret_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SecretShareApp</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>
<%= button_to("Log Out", sessions_path, :method => "delete") %>
</body>
</html>

app/views/secrets/index.html.erb
<h1><%= "#{@current_user.name}'s" %> SECRET(S)</h1>

<ul>
<% @secrets.each do |secret| %>
  <li>
    <%= secret.body %>
  </li>
<% end %>

</ul>

app/views/secrets/new.html.erb
<h1>New Secret</h1>

<%= form_for @secret do |f| %>
  <%= f.label :body, "All your secrets: " %>
  <%= f.text_field :body %>
  <%= f.submit "Create" %>
<% end %>

app/views/users/new.html.erb
<h1>Create User</h1>

<%= form_for @user do |f| %>
  <ul>
    <%= @user.errors.full_messages.join %>
    <%= f.label :name, "User Name:" %><br>
    <%= f.text_field :name %><br>
    <%= f.label :email, "Email:" %><br>
    <%= f.text_field :email %><br>
    <%= f.label :password, "Password:" %><br>
    <%= f.password_field :password %><br>
    <%= f.label :password_confirmation, "Confirm Password:" %><br>
    <%= f.password_field :password_confirmation %><br>
    <%= f.submit "SUBMIT TO ME!!!" %>
<% end %>
  </ul>